/**
 * iGEM Wiki Export API
 * Generates Markdown/HTML formatted reports ready for iGEM Wiki
 */

import { NextRequest, NextResponse } from 'next/server';

export interface WikiExportOptions {
  format: 'markdown' | 'html';
  title: string;
  projectName: string;
  teamName?: string;
  year?: number;
  sections: WikiSection[];
  includeCharts?: boolean;
  includeTables?: boolean;
  includeReferences?: boolean;
}

export interface WikiSection {
  type: 'text' | 'table' | 'chart' | 'image' | 'sequence' | 'dbtl' | 'team';
  title: string;
  content: any;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { format = 'markdown', title, projectName, sections, includeTables = true, includeReferences = true } = body as WikiExportOptions;

    if (format === 'markdown') {
      const markdown = generateMarkdown({ title, projectName, sections, includeTables, includeReferences });
      return new NextResponse(markdown, {
        headers: {
          'Content-Type': 'text/markdown; charset=utf-8',
          'Content-Disposition': `attachment; filename="${projectName.replace(/\s+/g, '_')}_wiki.md"`
        }
      });
    } else {
      const html = generateHTML({ title, projectName, sections, includeTables, includeReferences });
      return new NextResponse(html, {
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Content-Disposition': `attachment; filename="${projectName.replace(/\s+/g, '_')}_wiki.html"`
        }
      });
    }
  } catch (error) {
    return NextResponse.json(
      { error: 'Export failed', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}

function generateMarkdown(options: {
  title: string;
  projectName: string;
  sections: WikiSection[];
  includeTables: boolean;
  includeReferences: boolean;
}): string {
  const { title, projectName, sections, includeTables, includeReferences } = options;
  const year = new Date().getFullYear();
  
  let md = '';
  
  // Header
  md += `# ${title}\n\n`;
  md += `**Project:** ${projectName}  \n`;
  md += `**Year:** ${year}  \n`;
  md += `**Generated by:** FluBioStack  \n`;
  md += `**Date:** ${new Date().toISOString().split('T')[0]}  \n\n`;
  md += `---\n\n`;
  
  // Table of Contents
  md += `## Table of Contents\n\n`;
  sections.forEach((section, idx) => {
    md += `${idx + 1}. [${section.title}](#${section.title.toLowerCase().replace(/\s+/g, '-')})\n`;
  });
  md += `\n---\n\n`;
  
  // Sections
  sections.forEach((section) => {
    md += `## ${section.title}\n\n`;
    md += renderMarkdownSection(section, { includeTables, includeReferences });
    md += `\n---\n\n`;
  });
  
  // References
  if (includeReferences) {
    md += `## References\n\n`;
    md += `1. FluBioStack - Synthetic Biology Research Platform\n`;
    md += `2. iGEM Competition Guidelines\n`;
  }
  
  return md;
}

function renderMarkdownSection(section: WikiSection, options: { includeTables: boolean; includeReferences: boolean }): string {
  switch (section.type) {
    case 'text':
      return section.content.text || '';
      
    case 'table':
      if (!options.includeTables || !section.content.headers || !section.content.rows) return '';
      let table = `| ${section.content.headers.join(' | ')} |\n`;
      table += `| ${section.content.headers.map(() => '---').join(' | ')} |\n`;
      section.content.rows.forEach((row: string[]) => {
        table += `| ${row.join(' | ')} |\n`;
      });
      return table;
      
    case 'sequence':
      const seq = section.content.sequence || '';
      const formatted = seq.match(/.{1,60}/g)?.join('\n') || seq;
      return `\`\`\`\n${section.content.name || 'Sequence'}\nLength: ${seq.length} bp\n\`\`\`\n\n\`\`\`\n${formatted}\n\`\`\`\n`;
      
    case 'dbtl':
      const steps = section.content.steps || [];
      let dbtl = '';
      steps.forEach((step: any) => {
        dbtl += `### ${step.phase}: ${step.date}\n\n`;
        dbtl += `**Description:** ${step.description}\n\n`;
        if (step.result) dbtl += `**Result:** ${step.result}\n\n`;
        dbtl += `**Status:** ${step.status}\n\n`;
      });
      return dbtl;
      
    case 'chart':
      return `*[Chart: ${section.title}]*\n\n**Description:** ${section.content.description || 'See visualization above'}\n`;
      
    case 'team':
      return `**Team Members:** ${section.content.members?.join(', ') || 'TBD'}\n\n**Institution:** ${section.content.institution || 'TBD'}\n`;
      
    default:
      return '';
  }
}

function generateHTML(options: {
  title: string;
  projectName: string;
  sections: WikiSection[];
  includeTables: boolean;
  includeReferences: boolean;
}): string {
  const { title, projectName, sections, includeTables, includeReferences } = options;
  const year = new Date().getFullYear();
  
  const bodyContent = sections.map(section => {
    let content = renderHTMLSection(section, { includeTables, includeReferences });
    return `<section class="wiki-section">
      <h2>${section.title}</h2>
      ${content}
    </section>`;
  }).join('\n');
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - ${projectName}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { 
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 900px;
      margin: 0 auto;
      padding: 2rem;
      background: #f5f5f5;
    }
    .wiki-header {
      background: linear-gradient(135deg, #0B1020, #1a2040);
      color: white;
      padding: 2rem;
      border-radius: 12px;
      margin-bottom: 2rem;
    }
    .wiki-header h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    .wiki-header p { opacity: 0.8; font-size: 0.9rem; }
    .wiki-section {
      background: white;
      padding: 1.5rem;
      border-radius: 8px;
      margin-bottom: 1.5rem;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    .wiki-section h2 {
      color: #16BFDB;
      border-bottom: 2px solid #16BFDB;
      padding-bottom: 0.5rem;
      margin-bottom: 1rem;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1rem 0;
    }
    th, td {
      padding: 0.75rem;
      text-align: left;
      border: 1px solid #ddd;
    }
    th { background: #f0f0f0; font-weight: 600; }
    tr:nth-child(even) { background: #f9f9f9; }
    code, pre {
      background: #1a1a2e;
      color: #16BFDB;
      border-radius: 4px;
      font-family: 'Courier New', monospace;
    }
    pre {
      padding: 1rem;
      overflow-x: auto;
      margin: 1rem 0;
    }
    .sequence-label {
      background: #7E3AFF;
      color: white;
      padding: 0.25rem 0.75rem;
      border-radius: 4px 4px 0 0;
      display: inline-block;
      font-weight: 600;
      font-size: 0.85rem;
    }
    .sequence-block {
      background: #1a1a2e;
      color: #16BFDB;
      padding: 1rem;
      border-radius: 0 8px 8px 8px;
      font-family: 'Courier New', monospace;
      font-size: 0.8rem;
      line-height: 1.4;
      word-break: break-all;
      overflow-x: auto;
    }
    .dbtl-step {
      border-left: 4px solid #16BFDB;
      padding-left: 1rem;
      margin: 1rem 0;
    }
    .dbtl-step.completed { border-color: #16D88A; }
    .dbtl-step.in-progress { border-color: #FF9A1F; }
    .dbtl-step.planned { border-color: #9BA8D0; }
    .status-badge {
      display: inline-block;
      padding: 0.2rem 0.6rem;
      border-radius: 4px;
      font-size: 0.75rem;
      font-weight: 600;
    }
    .status-completed { background: #e8f5e9; color: #16D88A; }
    .status-in-progress { background: #fff3e0; color: #FF9A1F; }
    .status-planned { background: #e8eaf6; color: #9BA8D0; }
    .wiki-footer {
      text-align: center;
      padding: 2rem;
      color: #666;
      font-size: 0.85rem;
    }
    @media print {
      body { background: white; }
      .wiki-section { box-shadow: none; border: 1px solid #ddd; }
    }
  </style>
</head>
<body>
  <header class="wiki-header">
    <h1>${title}</h1>
    <p><strong>Project:</strong> ${projectName} &nbsp;|&nbsp; <strong>Year:</strong> ${year} &nbsp;|&nbsp; <strong>Generated by:</strong> FluBioStack</p>
  </header>
  
  <nav class="wiki-section">
    <h2>Table of Contents</h2>
    <ol>
      ${sections.map((s, i) => `<li><a href="#section-${i}">${s.title}</a></li>`).join('\n      ')}
    </ol>
  </nav>
  
  ${sections.map((section, i) => `
    <section class="wiki-section" id="section-${i}">
      <h2>${section.title}</h2>
      ${renderHTMLSection(section, { includeTables, includeReferences })}
    </section>
  `).join('\n')}
  
  ${includeReferences ? `
  <section class="wiki-section">
    <h2>References</h2>
    <ol>
      <li>FluBioStack - Synthetic Biology Research Platform <code>https://flubiostack.edu</code></li>
      <li>iGEM Competition Guidelines <code>https://igem.org</code></li>
    </ol>
  </section>
  ` : ''}
  
  <footer class="wiki-footer">
    <p>Generated by <strong>FluBioStack</strong> | ${new Date().toISOString()}</p>
  </footer>
</body>
</html>`;
}

function renderHTMLSection(section: WikiSection, options: { includeTables: boolean; includeReferences: boolean }): string {
  switch (section.type) {
    case 'text':
      return `<p>${section.content.text || ''}</p>`;
      
    case 'table':
      if (!options.includeTables || !section.content.headers || !section.content.rows) return '';
      const headers = section.content.headers.map((h: string) => `<th>${h}</th>`).join('');
      const rows = section.content.rows.map((row: string[]) => 
        `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`
      ).join('\n');
      return `<table>\n<thead><tr>${headers}</tr></thead>\n<tbody>${rows}</tbody>\n</table>`;
      
    case 'sequence':
      const seq = section.content.sequence || '';
      const name = section.content.name || 'Sequence';
      const length = seq.length;
      const formatted = seq.match(/.{1,60}/g)?.join('<br>') || seq;
      return `<div>
        <span class="sequence-label">${name} | Length: ${length} bp</span>
        <div class="sequence-block">${formatted}</div>
      </div>`;
      
    case 'dbtl':
      const steps = section.content.steps || [];
      return steps.map((step: any) => {
        const statusClass = step.status === 'completed' ? 'completed' : 
                           step.status === 'in_progress' ? 'in-progress' : 'planned';
        return `<div class="dbtl-step ${statusClass}">
          <strong>${step.phase}</strong> - ${step.date}
          <p>${step.description}</p>
          ${step.result ? `<p><strong>Result:</strong> ${step.result}</p>` : ''}
          <span class="status-badge status-${statusClass.replace('-', '')}">${step.status}</span>
        </div>`;
      }).join('\n');
      
    case 'chart':
      return `<p><em>[Chart: ${section.title}]</em></p><p>${section.content.description || ''}</p>`;
      
    case 'team':
      return `<p><strong>Team Members:</strong> ${section.content.members?.join(', ') || 'TBD'}</p>
              <p><strong>Institution:</strong> ${section.content.institution || 'TBD'}</p>`;
      
    default:
      return '';
  }
}
